version: '3.8'

services:
  beingdb:
    build: .
    volumes:
      # Persist stores between runs
      - ./git-store:/data/git-store
      - ./pack-store:/data/pack-store
      - ./snapshots:/data/snapshots

